### ISSUE TITLE
somethings u need 2 do

### ISSUE THREAD

**Issue by KiteAB** [EvanMeek/shengci.el#1]
- rename repo, current name is too bad
- write a readme.org file
- optimization codes
and all things i can help u 2 do, but u need move repo to kitpixel first
:laughing:

**Comment by KiteAB** [comment]
oops, and u can try submit it to melpa source

**Comment by EvanMeek** [comment]
This plugin is for Chinese user, so it name is very reasonale. I am writing README file. You are right, the code does need to be optimized, but due to my limited level, I may not be able to achieve what a standard, so PR. weelcome!

**Comment by KiteAB** [comment]
will pr later
