### ISSUE TITLE
一点小功能的请求

### ISSUE THREAD

**Issue by GinShio** [EvanMeek/shengci.el#2]
可以考虑增加从输入保存单词到生词本吗，比如 `shengci-input-word-and-save`。有时其他地方遇到的生词，如果想要加入到生词本需要先输入到buffer再捕获，显得比较麻烦

**Comment by EvanMeek** [comment]
> 可以考虑增加从输入保存单词到生词本吗，比如 `shengci-input-word-and-save`。有时其他地方遇到的生词，如果想要加入到生词本需要先输入到buffer再捕获，显得比较麻烦

已经实现了，你可以直接给capture word那个函数传个参数，参数就是一个字符串，代表一个英文单词。

**Comment by EvanMeek** [comment]
```emacs-lisp
;;  例如
(shengci-capture-and-save-word "hello")
(shengci-capture-and-save-word 'world)
;; 都可以
```

**Comment by EvanMeek** [comment]
既然没啥问题了，那我就关闭这个issue了.
